# Generated by Django 5.1 on 2025-06-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0002_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mob',
            field=models.CharField(max_length=15),
        ),
    ]
