# Generated by Django 5.1 on 2025-06-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_alter_order_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.CharField(max_length=7),
        ),
    ]
