# Generated by Django 5.2.2 on 2025-06-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
