# Generated by Django 5.1 on 2025-06-18 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_alter_order_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
