# Generated by Django 5.2.2 on 2025-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
