# Generated by Django 5.1 on 2025-06-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0007_alter_order_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pin',
        ),
    ]
