# Generated by Django 5.1 on 2025-06-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0008_remove_order_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pin',
            field=models.CharField(default='12', max_length=10),
        ),
    ]
